from django.urls import path
from . import views
from . import pfe_views
from . import import_views

urlpatterns = [
    # --- Excel account import ---
    path('import/students/', import_views.import_students, name='import_students'),
    path('import/teachers/', import_views.import_teachers, name='import_teachers'),
    # --- Department announcements ---
    path('announcements/create/', views.create_department_announcement, name='create_department_announcement'),
    path('announcements/', views.list_department_announcements, name='list_department_announcements'),
    # --- Forum detail & moderation ---
    path('forum/questions/<uuid:question_id>/', views.get_forum_question_detail, name='get_forum_question_detail'),
    path('forum/questions/<uuid:question_id>/delete/', views.delete_forum_question, name='delete_forum_question'),
    path('forum/answers/<uuid:answer_id>/delete/', views.delete_forum_answer, name='delete_forum_answer'),
    path('dashboard/stats/', views.get_admin_dashboard_stats, name='get_admin_dashboard_stats'),
    path('timetable/import/dry-run/', views.timetable_import_dry_run, name='timetable_import_dry_run'),
    path('timetable/import/commit/', views.timetable_import_commit, name='timetable_import_commit'),
    path('timetable/status/', views.get_timetable_publish_status, name='get_timetable_publish_status'),
    path('timetable/publish/', views.publish_timetable, name='publish_timetable'),
    path('timetable/unpublish/', views.unpublish_timetable, name='unpublish_timetable'),
    path('timetable/list/', views.list_timetable_slots, name='list_timetable_slots'),
    path('timetable/manual/create/', views.create_timetable_slot, name='create_timetable_slot'),
    path('timetable/manual/delete/', views.delete_timetable_slot, name='delete_timetable_slot'),
    path('timetable/export/ics/', views.export_timetable_ics, name='export_timetable_ics'),
    path('timetable/readiness/', views.get_timetable_readiness, name='get_timetable_readiness'),
    path('timetable/telemetry/', views.log_timetable_telemetry, name='log_timetable_telemetry'),
    path('add-classes/', views.create_classes, name='login'),
    path('get-classes/', views.get_classes, name='get_classes'),
    path('departments/get/', views.get_departments, name='get_departments'),
    path('departments/create/', views.create_department, name='create_department'),
    path('departments/assign-head/', views.assign_department_head, name='assign_department_head'),
    path('upload/schedule/', views.create_schedule, name='upload_schedule'),
    path('classes/schedule/', views.get_classes_schedule, name='get_classes_schedule'),
    path('teacher/schedule/', views.get_teacher_schedule, name='get_teacher_schedule'),
    path('teacher/get/', views.get_teachers, name='get_teachers'),
    path('students/get/', views.get_students, name='get_students'),
    path('students/update/', views.update_student, name='update_students'),
    path('students/delete/', views.delete_student, name='delete_students'),
    path('post/upload/', views.create_post, name='upload_post'),
    path('post/delete/', views.delete_post, name='get_posts'),
    path('posts/update/', views.update_post, name='update_post'),
    path('posts/get/announcement/', views.get_announcement_posts, name='get_posts'),
    path ('posts/get/lessons/', views.get_lesson_posts,name='lesson-posts'),
    path('forum/questions/create/', views.create_forum_question, name='create_forum_question'),
    path('forum/questions/answer/', views.answer_forum_question, name='answer_forum_question'),
    path('forum/questions/', views.get_forum_questions, name='get_forum_questions'),
    path('teacher/availability/set/', views.set_teacher_availability, name='set_teacher_availability'),
    path('teacher/surveillance-load/', views.get_teacher_surveillance_load, name='get_teacher_surveillance_load'),
    path('exam-calendar/manual/', views.create_exam_calendar_manual, name='create_exam_calendar_manual'),
    path('exam-calendar/excel/', views.create_exam_calendar_from_excel, name='create_exam_calendar_from_excel'),
    path('pfe/excel/', views.create_pfe_subjects_from_excel, name='create_pfe_subjects_from_excel'),
    path('pfe/jury/assign/', views.assign_pfe_jury, name='assign_pfe_jury'),
    path('pfe/teacher-quota/', views.get_pfe_teacher_quota, name='get_pfe_teacher_quota'),
    path('pfe/subjects/', pfe_views.list_pfe_subjects, name='list_pfe_subjects'),
    path('pfe/sessions/departments/', pfe_views.list_pfe_session_departments, name='list_pfe_session_departments'),
    path('pfe/sessions/unlock-head/', pfe_views.unlock_pfe_session_for_head, name='unlock_pfe_session_for_head'),
    path('pfe/sessions/seed-demo/', pfe_views.seed_pfe_session_demo, name='seed_pfe_session_demo'),
    path('pfe/students/', pfe_views.list_pfe_students, name='list_pfe_students'),
    path('pfe/subjects/assign-student/', pfe_views.assign_student_to_pfe_subject, name='assign_student_to_pfe_subject'),
    path('pfe/campaign/upsert/', pfe_views.upsert_pfe_campaign, name='upsert_pfe_campaign'),
    path('pfe/campaign/get/', pfe_views.get_pfe_campaign, name='get_pfe_campaign'),
    path('pfe/campaigns/', pfe_views.manage_pfe_campaigns, name='manage_pfe_campaigns'),
    path('pfe/campaigns/detail/', pfe_views.get_manage_pfe_campaign_detail, name='get_manage_pfe_campaign_detail'),
    path('pfe/campaigns/generate/', pfe_views.generate_manage_pfe_campaign_schedule, name='generate_manage_pfe_campaign_schedule'),
    path('pfe/campaigns/manual-assign/', pfe_views.manual_assign_pfe_presentation, name='manual_assign_pfe_presentation'),
    path('pfe/campaigns/auto-fit-leftovers/', pfe_views.auto_fit_unresolved_presentations, name='auto_fit_unresolved_presentations'),
    path('pfe/campaign/activate/', pfe_views.activate_pfe_campaign, name='activate_pfe_campaign'),
    path('pfe/campaign/quotas/set/', pfe_views.set_pfe_campaign_quota_overrides, name='set_pfe_campaign_quota_overrides'),
    path('teacher/availability/date-exception/set/', pfe_views.set_teacher_availability_date_exception, name='set_teacher_availability_date_exception'),
    path('teacher/availability/get/', pfe_views.get_teacher_availability, name='get_teacher_availability'),
    path('pfe/auto-assign/dry-run/', pfe_views.pfe_auto_assign_dry_run, name='pfe_auto_assign_dry_run'),
    path('pfe/auto-assign/commit/', pfe_views.pfe_auto_assign_commit, name='pfe_auto_assign_commit'),
    path('pfe/assignments/list/', pfe_views.list_pfe_assignments, name='list_pfe_assignments'),
    path('pfe/assignments/export/', pfe_views.export_pfe_assignments, name='export_pfe_assignments'),
    path('pfe/jury/unassign/', pfe_views.unassign_pfe_jury, name='unassign_pfe_jury'),
    path('pfe/simulation/seed/', pfe_views.seed_pfe_simulation_dataset, name='seed_pfe_simulation_dataset'),
]
