# Generated by Django 6.0.3 on 2026-04-26 15:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetablePublications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'timetable_publications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimetableTelemetry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
                ('event_name', models.CharField(max_length=120)),
                ('route', models.CharField(blank=True, max_length=180, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'timetable_telemetry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username can only contain letters and spaces', regex='^[A-Za-z ]+$')])),
                ('password', models.TextField()),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('niveau', models.TextField()),
                ('classe_section', models.CharField(choices=[('Prépa', 'Prepa Mpi'), ('L-LSI', 'L Lsi'), ('L-Mécanique', 'L Mecanique'), ('L-Energie', 'L Energie'), ('Cycle Ingénieur', 'Cycle Ingenieur')], default='Prépa', max_length=40)),
                ('classe_num', models.TextField()),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('department', models.TextField()),
                ('ncin', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='NCIN must be exactly 8 numerical digits', regex='^\\d{8}$')])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(23), django.core.validators.MaxValueValidator(65)])),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='ExamSessions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='api.classes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_sessions',
            },
        ),
        migrations.CreateModel(
            name='ForumQuestions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('class_id', models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.classes')),
            ],
            options={
                'db_table': 'forum_questions',
            },
        ),
        migrations.CreateModel(
            name='ForumAnswers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.forumquestions')),
            ],
            options={
                'db_table': 'forum_answers',
            },
        ),
        migrations.CreateModel(
            name='PFECampaigns',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('day_start_time', models.TimeField()),
                ('day_end_time', models.TimeField()),
                ('slot_duration_minutes', models.PositiveIntegerField(default=60)),
                ('break_duration_minutes', models.PositiveIntegerField(default=15)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('daily_cap_per_teacher', models.PositiveIntegerField(blank=True, null=True)),
                ('head_can_start', models.BooleanField(default=False)),
                ('availability_open', models.BooleanField(default=False)),
                ('schedule_generated', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pfe_campaigns', to='api.departments')),
            ],
            options={
                'db_table': 'pfe_campaigns',
            },
        ),
        migrations.CreateModel(
            name='PFEPresentationSlots',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('presentation_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentation_slots', to='api.pfecampaigns')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pfe_presentation_slots',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('lesson', 'Lesson'), ('announcement', 'Announcement')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('class_id', models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.classes')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('Lundi', 'Monday'), ('Mardi', 'Tuesday'), ('Mercredi', 'Wednesday'), ('jeudi', 'Thursday'), ('Vendredi', 'Friday'), ('Samedi', 'Saturday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.TextField()),
                ('subject', models.TextField()),
                ('class_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='api.classes')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='api.teachers')),
            ],
            options={
                'db_table': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('parent_contact', models.CharField(blank=True, max_length=8, null=True)),
                ('access_status', models.BooleanField(default=True)),
                ('class_id', models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.classes')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='PFESubjects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('student_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pfe_subjects_list', to='api.departments')),
                ('student', models.ForeignKey(blank=True, db_column='student_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pfe_subjects', to='api.students')),
                ('supervisor', models.ForeignKey(db_column='supervisor_id', on_delete=django.db.models.deletion.CASCADE, related_name='supervised_pfe_subjects', to='api.teachers')),
            ],
            options={
                'db_table': 'pfe_subjects',
            },
        ),
        migrations.AddField(
            model_name='departments',
            name='head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to='api.teachers'),
        ),
        migrations.CreateModel(
            name='PFECampaignRooms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.pfecampaigns')),
            ],
            options={
                'db_table': 'pfe_campaign_rooms',
                'unique_together': {('campaign', 'room_name')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.schedules')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.students')),
            ],
            options={
                'db_table': 'attendance',
                'unique_together': {('student', 'schedule', 'session_date')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailabilityDateExceptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context', models.CharField(choices=[('surveillance', 'Surveillance'), ('pfe', 'Pfe')], max_length=20)),
                ('availability_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('level', models.CharField(choices=[('preferred', 'Preferred'), ('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_exceptions', to='api.pfecampaigns')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, related_name='availability_date_exceptions', to='api.teachers')),
            ],
            options={
                'db_table': 'teacher_availability_date_exceptions',
                'unique_together': {('teacher', 'context', 'campaign', 'availability_date', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailabilities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context', models.CharField(choices=[('surveillance', 'Surveillance'), ('pfe', 'Pfe')], max_length=20)),
                ('day_of_week', models.CharField(choices=[('Lundi', 'Monday'), ('Mardi', 'Tuesday'), ('Mercredi', 'Wednesday'), ('jeudi', 'Thursday'), ('Vendredi', 'Friday'), ('Samedi', 'Saturday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('level', models.CharField(choices=[('preferred', 'Preferred'), ('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_availabilities', to='api.pfecampaigns')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='api.teachers')),
            ],
            options={
                'db_table': 'teacher_availabilities',
                'unique_together': {('teacher', 'context', 'campaign', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='PFETeacherQuotaOverrides',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_presentations', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_quota_overrides', to='api.pfecampaigns')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, related_name='pfe_quota_overrides', to='api.teachers')),
            ],
            options={
                'db_table': 'pfe_teacher_quota_overrides',
                'unique_together': {('campaign', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='PFEJuryAssignments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('encadreur', 'Encadreur'), ('rapporteur', 'Rapporteur'), ('president', 'President')], max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pfepresentationslots')),
                ('pfe_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_assignments', to='api.pfesubjects')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, related_name='pfe_jury_assignments', to='api.teachers')),
            ],
            options={
                'db_table': 'pfe_jury_assignments',
                'unique_together': {('pfe_subject', 'teacher', 'role')},
            },
        ),
        migrations.CreateModel(
            name='ExamSurveillanceAssignments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveillance_assignments', to='api.examsessions')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_surveillance_assignments', to='api.teachers')),
            ],
            options={
                'db_table': 'exam_surveillance_assignments',
                'unique_together': {('exam_session', 'teacher')},
            },
        ),
    ]
