# Generated by Django 6.0.3 on 2026-04-26 22:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfecampaigns',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('collecting_availability', 'Collecting Availability'), ('needs_manual_assignment', 'Needs Manual Assignment'), ('generated', 'Generated')], default='draft', max_length=40),
        ),
        migrations.CreateModel(
            name='StudentNotifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_notifications', to='api.pfecampaigns')),
                ('pfe_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notifications', to='api.pfesubjects')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_notifications', to='api.pfepresentationslots')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.students')),
            ],
            options={
                'db_table': 'student_notifications',
            },
        ),
        migrations.CreateModel(
            name='PFECampaignTeacherSubmissions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entries_count', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_submissions', to='api.pfecampaigns')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, related_name='pfe_campaign_submissions', to='api.teachers')),
            ],
            options={
                'db_table': 'pfe_campaign_teacher_submissions',
                'unique_together': {('campaign', 'teacher')},
            },
        ),
    ]
