# Generated by Django 5.2 on 2025-04-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_users_groups_users_is_active_users_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={},
        ),
    ]
