# Generated by Django 6.0.3 on 2026-04-30 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_posts_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetablepublications',
            options={},
        ),
        migrations.AlterModelOptions(
            name='timetabletelemetry',
            options={},
        ),
    ]
