# Generated by Django 5.2 on 2025-04-17 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_posts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'managed': False},
        ),
    ]
